# Generated by Django 4.2.7 on 2023-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default_shipping_address',
            field=models.BooleanField(default=False),
        ),
    ]
