# Generated by Django 4.2.7 on 2023-12-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_default_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
