# Generated by Django 4.2.7 on 2023-12-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name'),
        ('shop', '0011_remove_orderproducts_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='placed', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_by_quan_coast', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvariant')),
            ],
        ),
    ]
