# Generated by Django 4.2.6 on 2023-11-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_product_description_remove_product_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="product_variant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.productvariant"
            ),
        ),
    ]
