# Generated by Django 4.2.7 on 2023-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_orderproducts_product_variant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
