# Generated by Django 4.2.7 on 2023-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_product_description_alter_productvariant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
