# Generated by Django 4.2.7 on 2023-11-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name'),
        ('shop', '0006_alter_orderproducts_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.address'),
        ),
    ]
