# Generated by Django 4.2.7 on 2023-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_nba_player_alter_product_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='product_id',
        ),
    ]
