# Generated by Django 4.2.7 on 2023-12-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_orderproducts_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='product_variant_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
